-- MySQL Script generated by MySQL Workbench
-- Thu Sep 24 19:22:15 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`ID`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ID` (
  `idID` INT NOT NULL,
  `ID Сотр` VARCHAR(45) NULL,
  `ID Дол` VARCHAR(45) NULL,
  PRIMARY KEY (`idID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Сотрудники`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Сотрудники` (
  `ID сотрудника` INT NOT NULL,
  `Фамилия` VARCHAR(45) NOT NULL,
  `Имя` VARCHAR(45) NOT NULL,
  `Отчество` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID сотрудника`),
  CONSTRAINT `ID`
    FOREIGN KEY (`ID сотрудника`)
    REFERENCES `mydb`.`ID` (`idID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Должности`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Должности` (
  `ID Должности` INT NOT NULL,
  `Должность` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID Должности`, `Должность`),
  CONSTRAINT `ID`
    FOREIGN KEY (`ID Должности`)
    REFERENCES `mydb`.`ID` (`idID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
